# Replace all the comment with your configuration

mailer_config:
  enable_starttls_auto: #true / false
  address: #'smtp.example.com'
  port: #port_number
  domain: #"example.com"
  user_name: #'my_emailerm@example.com'
  password: #'my_password'
  authentication: #'plain'

web_page_config:
  google_analytics:
    account: #"'your_analytics_code'"
    domainName: #"'your_domain.com'"
    
secret_token: #'your_generated_secret_token'
